### PR TITLE
Add Bulgarian translation.

### PR DESCRIPTION
**Pull request by borj**
Add Bulgarian translation.

### CODE REVIEW

**Comment by decompil3d** [comment]
Thanks for the contribution! You'll need to update the test file too. See the output from the Actions workflow that I just started on your PR for what to look for.

**Comment by borj** [comment]
Hope it is OK now.

**Comment by decompil3d** [comment]
Looks like there is a typo in the test. Fix that up and then I can merge and release this when I have a moment at a computer. Thanks again!

**Comment by borj** [comment]
Yup, 2 symbols switched places :) Fixed.

**Pull request merged**
